version: "3.9"

x-env_file:
  env_file: &env_file
    - .env

services:
  backend:
    container_name: calendario-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file: *env_file
    depends_on:
      - db

  db:
    container_name: calendario-db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: *env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
